### ISSUE TITLE
Quest search results do not auto-appear after clearing

### ISSUE THREAD

**Issue by nyghtstalker** [HyperPlay-Gaming/hyperplay-desktop-client#1005]
### Describe the bug

After the user clears the search the results of the next search will not auto-appear

### Add logs

N/A

### Steps to reproduce

1. Go to the quests page
2. Search for and then select from the results
3. Clear the results and then search again
4. Observe that the results do not auto-appear

### Expected behavior

The results should always auto-appear

### Screenshots

![image](https://github.com/user-attachments/assets/5d397a61-c8f6-4cb8-abb2-1dfa78b4f25e)
![image](https://github.com/user-attachments/assets/47688615-4aa5-4d52-96ae-2afb75d7b8e6)
![image](https://github.com/user-attachments/assets/78ec049f-6567-4bc0-80d3-e95c522d40e5)

### hyperplay Version

Latest Stable

### System Information

- Windows 10
- hyperplay Version 0.17.3

**Comment by iamdavid0091** [comment]
This has been resolved.
