### ISSUE TITLE
Filter the game directory

### ISSUE THREAD

**Issue by jacobc-eth** [HyperPlay-Gaming/hyperplay-desktop-client#102]
As a HyperPlay user viewing the HyperPlay store, I'd like to filter the games directory, so that I can find the games most relevant to me.

**Description**

The HyperPlay games directory will ultimately contain LOTS of different games. We need to provide filters that allow the player to find the games that are most relevant to them.

For discussion, some likely filters we could provide include: genre, OS, and chain.

**AC**
Have drop down or other element that allows us to filter the store by: 
* All
* Installed - Y/N (only display when viewed in app)
* For OS, 5 options: Windows. Mac, and Linux
* Token gated - yes / no 
* Favorites (only display when viewed in app)
* Last Played (only display when viewed in app)
* Genre
* Chain
* Development State (Early Access, Stable)

**Comment by wswarren12** [comment]
Might add token gating as another filter option, so users can quickly filter those out.

**Comment by wswarren12** [comment]
Great clarification / addition, thanks @biliesilva

**Comment by biliesilva** [comment]
:)

**Comment by biliesilva** [comment]
@pimentel08 I will assign this task for you as you are working on the filters already.

**Comment by biliesilva** [comment]
Pimentel and I made some work in the filters based on the Team's suggestions and here is a sneak peek: 
![image.png](https://images.zenhubusercontent.com/632b7ad556a6e91b33441ad9/9ae66bde-f798-40c7-b78a-7fbf127d0081)

**Comment by awantoch** [comment]
Closing for: https://github.com/HyperPlay-Gaming/product-management/issues/195
