### ISSUE TITLE
UX: Navigation on SteamDeck

### ISSUE THREAD

**Issue by pimentel08** [HyperPlay-Gaming/hyperplay-desktop-client#112]

**Comment by biliesilva** [comment]
We can keep the same SteamDeck navigation icons without the need for styling for now. This also maintains players' familiarity with the menus:

![image.png](https://images.zenhubusercontent.com/632b7ad556a6e91b33441ad9/e4f1c0d3-bb59-4854-84c9-11f9302e1e20)

**Comment by iamdavid0091** [comment]
This is captured in this [Avion story](https://game7.avion.io/map/3zsNCKL4j7Ej9eGNY/zvcxKAoiZPLzjRn2A)
