### ISSUE TITLE
UI: Library for SteamDeck

### ISSUE THREAD

**Issue by pimentel08** [HyperPlay-Gaming/hyperplay-desktop-client#115]

**Comment by biliesilva** [comment]
![SteamDeck-Library1.png](https://images.zenhubusercontent.com/632b7ad556a6e91b33441ad9/0f20c8be-189e-4901-bc5d-1844ea54c398)

![SteamDeck-Library_List.png](https://images.zenhubusercontent.com/632b7ad556a6e91b33441ad9/fc5022da-9a3c-4ff7-afd1-3a9c13d6fdb2)

**Comment by iamdavid0091** [comment]
This is captured in this [Avion story](https://game7.avion.io/map/3zsNCKL4j7Ej9eGNY/zvcxKAoiZPLzjRn2A)

**Comment by awantoch** [comment]
@iamdavid0091 to sync with @flavioislima on remaining bugs for the SteamDeck

**Comment by awantoch** [comment]
@biliesilva to take design lead for any SteamDeck changes
