### ISSUE TITLE
Steamwebhelper suddenly broke

### ISSUE THREAD

**Issue by Tango1223** [HyperPlay-Gaming/hyperplay-desktop-client#1161]
### Describe the bug

Ive been using hyper play for 3 or 2 months now, I'm using wine on Mac. I got this message "Steamwebhelper is not responding" one day. Then when I try to download some window supported steam games it doesn't work (used to)

Note that: I factory reset my Mac due to some software malfunction

### Add logs

I don't have no logs

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

I expected steam to launch on hyper play, wine is updated so is hyper play.

### Screenshots

N/A

### hyperplay Version

Latest Stable

### System Information

- OS [e. g. "Ubuntu"]: 
- hyperplay Version [e. g. 2.1.1]:

### Additional information

This hadn't happened since I started using hyerplay to use window steam on Mac. (first time) this also happened when I factory reset my Mac.

**Comment by flavioislima** [comment]
Hi!
Sorry about that. Steam released a new version now that updated it's webview to a new version of CEF (Chromium) and this broke the app on macOS when using the compatibility layer.
We are working on a fix for that on our end.
