### ISSUE TITLE
Adjust my analytics settings

### ISSUE THREAD

**Issue by jacobc-eth** [HyperPlay-Gaming/hyperplay-desktop-client#129]
As a user who previously opted-in or out of analytics, I'd like to adjust my analytics settings in the settings menu, so that these settings will fit my expectations.

**Description**

This is adding the ability to off and on analytics in the settings menu. This option probably makes the most sense under Settings -> General.

**Comment by BrettCleary** [comment]
This was already possible here: https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/blob/d63943656578af0621e2396bdb6c9e67c52a265e/src/frontend/screens/Settings/components/ParticipateInMetrics.tsx#L7.

Updated to the new design here:
https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/pull/258
