### ISSUE TITLE
SDK session persistence - mobile reconnection alert.

### ISSUE THREAD

**Issue by biliesilva** [HyperPlay-Gaming/hyperplay-desktop-client#132]
We will need to implement some sort of UI element that says something like: "Connecting: Re-open MetaMask Mobile to re-establish connection" ahead of the confirmation. We will need designs for this along the same lines as our previous messages when a confirmation is pending on mobile, but these will basically just require the user re-open the app on their device.

**Comment by jacobc-eth** [comment]
The upcoming MetaMask SDK version has breaking changes, and it is quite important we take steps around this.

**Comment by jacobc-eth** [comment]
This is waiting on feedback from the MetaMask team.

**Comment by jacobc-eth** [comment]
wasn't this already implemented, @BrettCleary ?

**Comment by awantoch** [comment]
confirmed with @BrettCleary we can close this, real implementation doesn't quite work this way
