### ISSUE TITLE
Download the non-stable / beta version of a game

### ISSUE THREAD

**Issue by jacobc-eth** [HyperPlay-Gaming/hyperplay-desktop-client#142]
As a player who wants to try a game's beta release, I'd like to download the non-stable / beta version of the game, so I can get the latest features even before they are stable.

**Description**

This is a setting the player can enabled in the HyperPlay client to receive the beta / unstable build.

**Comment by BrettCleary** [comment]
Client integration working here https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/pull/257 with a dummy json file for hyperplay release data

Once valist has integrated the new data structure to HyperPlay game releases. I will remove the dummy json and retest

**Comment by awantoch** [comment]
Ready APIs and in-progress UI for this available in this PR: valist-io/hyperplay-dev#61

The store PR to integrate the new API is in progress here: HyperPlay-Gaming/hyperplay-store#20
