### ISSUE TITLE
Landing Page EthDenver alert

### ISSUE THREAD

**Issue by pimentel08** [HyperPlay-Gaming/hyperplay-desktop-client#146]
Alert at the top of the Landing Page with copy about the HyperPlay booth location. Should include the ability to close the alert.

[Figma Link](https://www.figma.com/file/729ANWXb7TtDZD5mj84qbc/Landing-Page?node-id=1051%3A582&t=sakykCo6xfvgr1HJ-4)

**Comment by biliesilva** [comment]
We can close this one.
