### ISSUE TITLE
Download Toast Notification

### ISSUE THREAD

**Issue by biliesilva** [HyperPlay-Gaming/hyperplay-desktop-client#150]
As a user of HyperPlay, I would like to see an indication of a game being downloaded visible on any screen.  

Acceptance criteria: 

- Have a pause and cancel download button with a confirmation modal;
- The user can close/minimize the notification.

**Comment by jacobc-eth** [comment]
Is this okay to move to engineering ready @biliesilva ?

**Comment by biliesilva** [comment]
@jacobc-eth Yes :)

**Comment by stormcakes** [comment]
Verified :)
