### ISSUE TITLE
UI fixes for alpha launch

### ISSUE THREAD

**Issue by jacobc-eth** [HyperPlay-Gaming/hyperplay-desktop-client#159]
1. Remove CSS rule that is forcing all caps in onboarding flow and side navbar
2. MetaMask Mobile Learn More link is pointing to Game7.io, should point to the FAQ in developer docs
3. "Please close out of your browser ..." -> "Please close your browser and try again."
4. If possible, make dapp title "//:file" -> "HyperPlay" or something similar
5. If possible, collapse the sidebar on Portfoliio view
6. "DISCORD" -> "Discord"
7. "CONNECTED" -> "Connected"
8. Ethereum address should not be all caps
9. Move MetaMask to menu sidebar with nesting

**Comment by BrettCleary** [comment]
1, 2, 3, 6, 7, 8, 9 are now implemented as of commit 97b0819ad7931dd8dac4007c98c0efb81b23656c on https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/pull/161

**Comment by jacobc-eth** [comment]
5 is also done here. I think the only remaining items is (4), the file:// dapp name.
