### ISSUE TITLE
Add a popup button to homescreen view

### ISSUE THREAD

**Issue by jacobc-eth** [HyperPlay-Gaming/hyperplay-desktop-client#178]
When viewing the homescreen view of MetaMask, show a button to open the popup.

**Comment by wswarren12** [comment]
@pimentel08 is this ticket also solved by your idea of creating a header in ticket #232? I think you already have a place in that design for the connected account to show up, which should serve as the button to pop up MetaMask (given that existing MM users would be used to that). 

@jacobc-eth lmk if that makes sense to you as well and I'll close this ticket and combine with the header ticket.

**Comment by pimentel08** [comment]
Yes, I was thinking along the same lines. A button similar to a Chrome plugin button for the MM pop-up that would live in the top nav. If we all agree, it would makes sense to me to combine this ticket with #232.
