### ISSUE TITLE
Enter the private access code for a game

### ISSUE THREAD

**Issue by jacobc-eth** [HyperPlay-Gaming/hyperplay-desktop-client#190]
As a player who received a special beta code, I'd like enter the beta code to access an unpublished game.

**Description**

We need to be able to inject private access keys from Valist protocol (currently still being implemented by the Valist team), in order to give players access to an unpublished game.

**AC**

*   add game to library even though it is unpublished in the HyperPlay Store.
*   require a signature and associate the private access code with the active wallet

**Comment by biliesilva** [comment]
First Design Iteration: 
![image.png](https://images.zenhubusercontent.com/632b7ad556a6e91b33441ad9/5372aa03-6020-477d-80c2-0a262eaa3b8a)

**Comment by biliesilva** [comment]
Adding the code from the Library: 

![image.png](https://images.zenhubusercontent.com/632b7ad556a6e91b33441ad9/f9d0a300-5589-447d-9dc9-6a58cd655abc)

**Comment by pimentel08** [comment]
Design update
![Screenshot 2023-06-20 at 3.50.35 PM.png](https://images.zenhubusercontent.com/63641b290f003701b0c099dc/0ab8821e-7642-497e-8b54-d90d4598595f)

**Comment by pimentel08** [comment]
See ticket #372
