### ISSUE TITLE
Be prompted to setup a compatibility library

### ISSUE THREAD

**Issue by jacobc-eth** [HyperPlay-Gaming/hyperplay-desktop-client#191]
As a user on MacOS or Linux, I'd like HyperPlay to auto-install a compatibility library relevant to my OS if I launch a Windows game on my OS.

**Description**

This story is to make a smoother process of getting compatibility libraries installed for users who may not already have them. This story probably needs discussion and additional grooming.

**Comment by wswarren12** [comment]
By compatibility library do you mean Wine? If so, I totally agree that automatically installing the most recent stable version of Wine makes sense to abstract that process away from the end-user. 

We'd probably need a second ticket for installing non-stable, more recent releases when required by a particular game.

**Comment by flavioislima** [comment]
We should have a way to specify the wine/proton version in which the game was tested. We can also specify wine-latest or proton-get-latest if the game runs fine on the latest releases. 

If we have this information, along with other information like dependencies to install using winetricks, we can run them on the first launch. 

If we don’t have this information, we can download the latest wine version on launch in case none was detected and try to launch the game anyway.

**Comment by jacobc-eth** [comment]
I think we already finished this story. can you confirm @flavioislima ?

**Comment by flavioislima** [comment]
> I think we already finished this story. can you confirm @flavioislima ?

Yes. This is done.
