### ISSUE TITLE
See my app version

### ISSUE THREAD

**Issue by jacobc-eth** [HyperPlay-Gaming/hyperplay-desktop-client#192]
As a HyperPlay user, I'd like to see the current version of my app, so they I know that I'm on the latest version.

**Description**

Currently, we've replaced the app version UI elements of Heroic with allet related features. As a result, users can't easily see their current app version. We need to find other prominent places to display the app version

**Comment by biliesilva** [comment]
How about having it on the bottom of the sidebar menu? 

![image.png](https://images.zenhubusercontent.com/632b7ad556a6e91b33441ad9/323b633f-e394-4c38-aa38-1c92c337386e)

**Comment by jacobc-eth** [comment]
@biliesilva I think we're probably going to need to add a small text link in that position that says "Switch Account" or "Switch Wallet" since so many people keep on clicking on the wallet button expecting it to give them the wallet homescreen rather than the switch wallet flow. It's one of the top UX confusions I've seen over and over again.

Do you think it would be work to migrate the app version to maybe the bottom right corner, or even just place it inside of Settings?

**Comment by biliesilva** [comment]
We are working on some options for this Switch wallet UX issue. 

For the version, we have it on Settings > Log, but we can try to find a better place if the users still having problems finding it: ![image.png](https://images.zenhubusercontent.com/632b7ad556a6e91b33441ad9/0ee48712-b819-48c4-a0a0-c53545f8aade)

**Comment by biliesilva** [comment]
Moved under Settings / General: 

![image.png](https://images.zenhubusercontent.com/632b7ad556a6e91b33441ad9/8a04aa06-1fc1-4dbd-8f3a-032c9d12d795)

**Comment by jacobc-eth** [comment]
solid solution @biliesilva  ^

**Comment by BrettCleary** [comment]
added here https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/pull/313
