### ISSUE TITLE
See that HyperPlay supports all EVM chains

### ISSUE THREAD

**Issue by jacobc-eth** [HyperPlay-Gaming/hyperplay-desktop-client#193]
As a person viewing the HyperPlay website, I'd like to see a graphic explaining that HyperPlay supports all EVM chains, so I know I don't need to demand a protocol specific integration of my chain.

**Description**

Currently, several protocols (Optimism, Skale, Aurora, and others) are requesting revision to  the chain list presented on the homepage of the HyperPlay website. I want us to replace what looks like a list with an artistic graphic that will seem more chain agnostic. 

Chains in the graphic for now: Ethereum, Optimism, Arbitrum, zkSync, IMX, StarkNet, Aurora, Avalanche, Harmony, Polygon, BNB chain, Mantle, and SKALE.

Underneath the artistic graph, we can add language that says:

Chain-agnostic: HyperPlay supports all MetaMask supported chains

**Comment by pimentel08** [comment]
The text is too long which forces design to decrease the size. Could we condense it to increase the size? Maybe something like, "All EVM chains supported" or "MetaMask supported chains"

**Comment by biliesilva** [comment]
@jacobc-eth could you check what chains you wrote in this ticket we will show exactly on the website?

**Comment by jacobc-eth** [comment]
This list looks good. The important way is that we make some solid way to dynamically update it.

**Comment by jacobc-eth** [comment]
This is already done.
