### ISSUE TITLE
Find a "Play with HyperPlay" button

### ISSUE THREAD

**Issue by jacobc-eth** [HyperPlay-Gaming/hyperplay-desktop-client#195]
As a player navigating to the website of a web3 game, I'd like to find a "Play with HyperPlay" button on the website of the game that I'm playing, so that I will be taken to the store page of the game and know where to find HyperPlay.

**Description**

These buttons will link to the game's page on the Store. The store will detect whether the store is being viewed in HyperPlay (Give "Add to Library" button) OR if the store is being viewed in browser (show "Download HyperPlay" button instead).

 This story covers creating a suite of embeddable buttons for us on third party sites that let the players know that the game can be downloaded through HyperPlay.

**AC**

*   Design should include a variety of sizes, layouts, and color schemes to match the diversity of sites for our games
* Take player to the store, and detect the progression path based on Window.Api
* If HyperPlay isn't installed, route the player to the HyperPlay download page

**Comment by pimentel08** [comment]
https://www.figma.com/file/WS1FGyynDR0W3NEQouORPv/Venus---Design-System-PRO?node-id=2351%3A19928&t=DQCMd2epcJK8nZ4o-4

**Comment by pimentel08** [comment]
![Screenshot 2023-03-16 at 9.44.55 PM.png](https://images.zenhubusercontent.com/63641b290f003701b0c099dc/34f9890b-2feb-49a1-a3d4-8ee4a835fe87)

**Comment by BrettCleary** [comment]
Can we make these images available on hyperplay.xyz/badges similarly to how [apple app store](https://developer.apple.com/app-store/marketing/guidelines/) and [google play store](https://play.google.com/intl/en_us/badges/) do it? 

Looks like they provide png, svg, and eps.

**Comment by pimentel08** [comment]
![store badge page.png](https://images.zenhubusercontent.com/63641b290f003701b0c099dc/7ed5db54-ad5b-4476-bcd3-ebae8051c496)

**Comment by pimentel08** [comment]
![Screenshot 2023-04-14 at 3.14.19 PM.png](https://images.zenhubusercontent.com/63641b290f003701b0c099dc/899ac7d6-3cd0-448a-8223-118b0fc57f9a)

The art can be found here:
All badges

**Stacked**
https://github.com/HyperPlay-Gaming/branding-resources/blob/main/Store%20badge-stacked.zip

**Get**
https://github.com/HyperPlay-Gaming/branding-resources/blob/main/Store%20badge-Get.zip

**Play**
https://github.com/HyperPlay-Gaming/branding-resources/blob/main/Store%20badge-play.zip

**Tag**
https://github.com/HyperPlay-Gaming/branding-resources/blob/main/Store%20badge-tag.zip

**Logo**
https://github.com/HyperPlay-Gaming/branding-resources/blob/main/Store%20badge-logo.zip

**Comment by pimentel08** [comment]
Can we have the download links + buttons automatically start downloading instead of taking a user to our github page?

**Comment by BrettCleary** [comment]
PR deployment here: https://hyperplay-website-git-feat-badgespage-hyperplay.vercel.app/badges

It looks different to the figma page due to the website still using the old design system but should suffice for now. Pimentel and I have discussed adding a separate card to update the website's design system.

Do we still need the embeddable button @jacobc-eth ? I believe this was requested because it was thought the button would perform some complex functionality to check if HP was installed and deep link to the game. But this card has evolved since it was first made and now will just link to the game's store page.

**Comment by jacobc-eth** [comment]
Yeah, probably no longer needed as an embed, but we should make the visual assets from the designs part of our brand resources to help devs who want assets for their links.
