### ISSUE TITLE
Dark font color in ''Choose Language'' dropdown

### ISSUE THREAD

**Issue by maxbidding** [HyperPlay-Gaming/hyperplay-desktop-client#198]
### Describe the bug

![Screenshot (1)](https://user-images.githubusercontent.com/106282381/225005470-25cb0852-2f4a-4d48-87fb-29c921892460.png)

### Add logs

(12:52:46) INFO:    [Backend]:          Loading MetaMask extension
(12:52:46) INFO:    [Connection]:       Connectivity: check-online
(12:52:46) INFO:    [Connection]:       Pinging external endpoints
(12:52:46) INFO:    [Backend]:          Creating abort controller for legendary-version
(12:52:46) INFO:    [Legendary]:        Running command: C:\Users\George\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary --version
(12:52:47) INFO:    [Legendary]:        Legendary location: C:\Users\George\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary
(12:52:47) INFO:    [Gog]:              GOGDL location: C:\Users\George\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\gogdl
(12:52:47) INFO:    [Gog]:              GOGDL location: C:\Users\George\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\gogdl
(12:52:47) INFO:    [Backend]:          MetaMask extension loaded
(12:52:47) WARNING: [Backend]:          Protocol already registered.
(12:52:47) INFO:    [Connection]:       Connectivity: online
(12:52:47) INFO:    [Backend]:          User Not Found, removing it from Store
(12:52:47) INFO:    [Backend]:          Deleting abort controller for legendary-version
(12:52:47) INFO:    [Backend]:          Creating abort controller for gogdl-version
(12:52:47) INFO:    [Gog]:              Running command: C:\Users\George\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\gogdl --version
(12:52:48) INFO:    [Backend]:          Deleting abort controller for gogdl-version
(12:52:48) INFO:    [Backend]:          Auto Updater found version: 0.0.9 released on 2023-03-09T00:48:09.445Z with name 0.0.9
(12:52:48) INFO:    [Backend]:          Loading Screen Ready
(12:52:48) INFO:    [Backend]:          Frontend Ready
(12:52:52) INFO:    [Backend]:          

HyperPlay Version: 0.0.9
Legendary Version:  0.20.32 Dark Energy (hotfix #6)
GOGdl Version: 0.6
OS: Microsoft Windows 11 Home KERNEL: 10.0.22621 ARCH: x64
CPU: Intel Core™ i7-8750H @2.2
RAM: Total: 31.88 GiB Available: 24.31 GiB
GRAPHICS: GPU0: NVIDIA GeForce RTX 2070 with Max-Q Design VRAM: 8192MB DRIVER: 531.18

(12:52:53) INFO:    [Backend]:          Starting the Download Queue

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

White font color

### hyperplay Version

Latest Stable

### System Information

- OS [e. g. "Ubuntu"]: 
- hyperplay Version [e. g. 2.1.1]:

**Comment by nyghtstalker** [comment]
No longer occurring
