### ISSUE TITLE
Interactions that open in a new window/tab are broken. ie. Buy ETH does not open page to complete tx 

### ISSUE THREAD

**Issue by wswarren12** [HyperPlay-Gaming/hyperplay-desktop-client#222]
**Describe the bug**
The purchase crypto option as part of the MetaMask portfolio tab doesn't work, because once you select Sardine or MoonPay the app doesn't open a browser window where you can complete the purchase. 

**Add logs**
x

**Steps to reproduce**
Create a new MetaMask wallet within HyperPlay 
Navigate to "Portfolio" tab 
Click "Buy" 
Select "Credit / Debit" 
Enter dollar amt and Get Quotes 
Select Moonpay or Sardine 
See modal saying complete purchase on Sardine (or Moonpay) 

**Expected Results**
A window would open in the browser where I could complete my purchase 

**Actual Results**
Nothing happens

Screenshots
![Screen Shot 2023-03-22 at 4.21.55 PM.png](https://images.zenhubusercontent.com/6412916cefdd845c6d180e53/6509f7c9-e2b1-47e8-85bc-d30e0c90a291)

hyperplay Version
main branch from GitHub

System Information
x

Additional information
No response

**Comment by jacobc-eth** [comment]
This is actually a larger issue that all websites that have links that open in a new tab or window cannot progress. This breaks lots of things in the MetaMask portfolio view, and it also breaks any browser games that have interactions in multiple tabs (ie. DeFi Kingdoms).

**Comment by jacobc-eth** [comment]
I've gone ahead and increased the priority level of this card because of the number of things it is breaking.

**Comment by flavioislima** [comment]
Looking at the code, we are not allowing popups on the portfolio webview and probably not on the new game browser windows, should be simple to solve though.

**Comment by hellowodl** [comment]
@flavioislima 

The error related to this specific case seems to be `Refused to set unsafe header "Accept-Encoding"`

**Comment by hellowodl** [comment]
> This is actually a larger issue that all websites that have links that open in a new tab or window cannot progress. This breaks lots of things in the MetaMask portfolio view, and it also breaks any browser games that have interactions in multiple tabs (ie. DeFi Kingdoms).

The second issue you've mentioned is more of a UX issue I think.
When I open a new tab/popup in eg. Defi Kingdoms, the overlay isn't baked into the new tab/popup, transactions need to be approved in the main window.

I'll create another ticket for that.

As for the specific issue mentioned within this issue, it has been fixed and is pending approval :)

**Comment by hellowodl** [comment]
@jacobc-eth I've created a new issue under #245 in respects to the DefiKingdom issues.

Does this issue describe the issue you were having?
