### ISSUE TITLE
Cross-platform overlay support

### ISSUE THREAD

**Issue by jacobc-eth** [HyperPlay-Gaming/hyperplay-desktop-client#227]
Issues with cross-platform overlays and proprietary game engines were reported by the Altiros team.  This card is migrated from a bug report to an overall feature enhancement for supporting the overlay on all OSes and game engines.

"We are currently testing game launch from HyperPlay Store and there's a problem with signature request. When we launch a game metamask opens in launcher window (we use extension) and after signing player is redirected to game window, this is ok. But if option Minimize After Launch is On launcher goes to tray automatically before showing metamask window with signature request. Player should guess on his own that he should reopen the launcher from tray, and there he will see the metamask window. This is very bad UX case.

Also we tested the signature request after game launch, but game just locks and waits for signature. And we see that signature request still opens only in launcher and not in game window (and not in browser, we thought that forcing browser launch could be one of possible options). So user still need to guess what to do and switch windows manually.

There's no indication on Windows whatsoever that player should sign, not even blinking in task bar."

**Comment by BrettCleary** [comment]
The overlay is visible with `Minimize After Launch` enabled. Tested with Defi Kingdoms and MoonBlasters. 

The issue is that the overlay is not working with Altiros. I seem to recall they are using a Java based game engine so perhaps that is causing some issue. I can see that injection finds their process correctly and correctly injects the dll but the overlay is not drawn. 

Do we know what game engine they are using and if it is using DirectX?

**Comment by AhriWindway** [comment]
Hi! I am developer from Altiros team.
We use LWJGL , which is based on OpenGL. And yes, it is Java.
I have an idea about the source of this problem. We use C++ wrapper to launch the game on Windows. Basically, it launches, sets some environment variables, launches JVM (only here graphic context appears) and hangs in background until JVM is destroyed. 
So, if you do dll injection into this wrapper, probably it won't work?

If you need any further info or any tests from our side, let me know.

**Comment by jacobc-eth** [comment]
Currently, the overlay implementation is incomplete on games that require OpenGL and don't support DirectX. We're still working on a solution for this, and are looking to bring this into our current sprint.

**Comment by BrettCleary** [comment]
this was shipped in 0.4.0
