### ISSUE TITLE
Add header with HyperPlay Store and Account buttons 

### ISSUE THREAD

**Issue by wswarren12** [HyperPlay-Gaming/hyperplay-desktop-client#232]
As a new HyperPlay user, I want a quick way to navigate to the HyperPlay store from my Library, so that I can find and add the games I want to play. 

**Description**

The Library page is where new users land and effectively the homepage for returning users. We want an easy way for them to navigate to our HyperPlay store, so that they can add more games to their library and spend more time playing games on HyperPlay. 

**AC**
* A redesigned header nav bar that makes the library a prominent button.

**Comment by pimentel08** [comment]
Alternatively, we could have a top nav for the most important items (HyperPlay Store, Library, Achievements (tbd), Account Login/Connect Wallet) that would be persistent at the top. We would reserve the side navigation for more admin/settings type of actions.

**Comment by biliesilva** [comment]
I had written something earlier here but it seems I forgot to send it 🙃. 

We can use as an example one of the suggestions we have in Desktop UI Figma (graveyard). I think this is a more suitable solution since we have many items in the side menu and it can end up being visually polluted.

Here the example:
![image](https://user-images.githubusercontent.com/61093873/228352974-1eb020da-bbbb-4b52-b9c9-5577cc86e385.png)

**Comment by wswarren12** [comment]
Updated this ticket to reflect the suggestion we add a top navbar for highlight the stores.

**Comment by pimentel08** [comment]
Top Navigation with store tabs makes it easier to navigate from store to store. It's also more prominent. 
![Screenshot 2023-04-17 at 2.40.42 PM.png](https://images.zenhubusercontent.com/63641b290f003701b0c099dc/3b4d53cc-8c57-4426-ba27-d8a3c7274b6e)

Accounts can all be found under a single account component.
![Screenshot 2023-04-17 at 2.42.19 PM.png](https://images.zenhubusercontent.com/63641b290f003701b0c099dc/28ee10ec-1bc9-461b-85e8-14a2620521fe)

**Comment by pimentel08** [comment]
https://www.figma.com/file/WS1FGyynDR0W3NEQouORPv/HyperPlay-Design-System?node-id=2279-18217&t=xy2eeXWIHcASAK5f-4

**Comment by biliesilva** [comment]
My suggestion here is to match the size of the account component with the dropdown menu.

**Comment by pimentel08** [comment]
Default state view:
<img width="987" alt="Screenshot 2023-04-17 at 4 02 42 PM" src="https://user-images.githubusercontent.com/93540327/232628512-e0fdfce5-4037-4fc6-b836-f54cd93a9738.png">

**Comment by biliesilva** [comment]
And if we give it more padding?

**Comment by pimentel08** [comment]
We can also remove the down-arrow the action is a hover effect and not a click-to-open effect. That is if we want to add more padding.

**Comment by pimentel08** [comment]
https://www.figma.com/file/WS1FGyynDR0W3NEQouORPv/HyperPlay-Design-System?node-id=2738-18025&t=JUseRW7zINcrRr94-4

**Comment by stormcakes** [comment]
This is a part of this i believe: https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/pull/293 so should be g2g for closing.
