### ISSUE TITLE
See MetaMask popup without a hotkey

### ISSUE THREAD

**Issue by jacobc-eth** [HyperPlay-Gaming/hyperplay-desktop-client#237]
As a player enjoying a game with in-game transactions using the MM browser extension, I'd like the browser extension to appear over the game without having to press a hotkey, so that I can approve transactions with less friction.

**Description**

Currently, our overlay is firing the overlay to show a notification that the player needs to press a hotkey to see the transaction, which adds an additional layer of friction over approving the transaction directly in a browser.

We should show the browser extension automatically any time there is an incoming transaction request. We should ALSO still show the notification in bottom right corner to that players know how to dismiss the browser extension. Potentially in a future story, we might adjust how the instructions to dismiss the overlay are shown, but that is out of scope for this story.

**AC**

* Show the MM popup without manual hotkey press
* Keep the notification mentioning Alt + X so that the player knows to to hide the popup if they want to.

**Comment by BrettCleary** [comment]
Could we add a setting so that the user can toggle this? If I'm playing a competitive game, I'd be really annoyed if metamask popped up and got me killed but if it's a game like defi kingdoms, then it'd be nice for it to just pop up like you mentioned

**Comment by wswarren12** [comment]
Don't know if you all have separately discussed, but I like @BrettCleary 's idea here for the same reasons he outlined. It's nice to have the MM pop up work automatically, except in the situations where it'd could be a huge hassle. 

Not sure how many of the real-time combat games have transactions built into combat, but having this setting could at least be a follow up ticket, if we're not worried about this right now.

**Comment by BrettCleary** [comment]
https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/pull/249 automatically shows the popup in browser and desktop games.

I agree with @wswarren12. I didn't implement the setting to toggle the extension auto show in this pr though. I think a follow up ticket would be great since it's a low priority right now. Great suggestion @wswarren12
