### ISSUE TITLE
Game's Library card is stuck in playing mode after closing out of game window (DeFi Kingdoms) 

### ISSUE THREAD

**Issue by wswarren12** [HyperPlay-Gaming/hyperplay-desktop-client#250]
**Game**: DeFi Kingdom 

**Description**:  I clicked out of the DeFi Kingdom's game window in order to close the game, but the card in the Library thinks I'm still playing and the stop button doesn't work. 

**Steps to Reproduce**
1. Open DeFi Kingdoms 
2. Go to one of the worlds 
3. Close out the windows associated with the game 
4. Try to click the "Stop Playing" button on the game's card in the HyperPlay Library 

**Expected Results**: Clicking on "Stop Playing" would update the game's state to closed / not playing. Or closing the windows associated with the game would do this (ideally, but get this might not be possible with browser games). 

**Actual Results**: Game is stuck in playing mode. 

![Screen Shot 2023-04-05 at 3.45.47 PM.png](https://images.zenhubusercontent.com/6412916cefdd845c6d180e53/d008af0e-7aa8-446b-a705-0cc7d96c006a)

**Comment by jacobc-eth** [comment]
We believe this issue is resolved now, but let's reopen if it is rediscovered.
