### ISSUE TITLE
Support browser and installable versions for the same game

### ISSUE THREAD

**Issue by BrettCleary** [HyperPlay-Gaming/hyperplay-desktop-client#253]
options are:

1. show two game cards. one for browser game and another for installable upon adding the game to library
- the browser game card would need to have the browser game icon shown on the card to distinguish the two
2. We can have a single game card and show a modal just the first time the player plays (when he has both installed), and a checkbox to add which one is the favorite (always launch the chosen version). If they wants to switch, we show this option to switch in the context menu. We will also show this option on the game page.

**Comment by biliesilva** [comment]
For option 1 (have two cards). Would be less confusing having two different game images (art cover) if this is possible with the Game Developers.
