### ISSUE TITLE
Users without MetaMask installed see option to import from Brave

### ISSUE THREAD

**Issue by jacobc-eth** [HyperPlay-Gaming/hyperplay-desktop-client#268]
### Describe the bug

Users with a fresh Brave install and a fresh HyperPlay install are seeing the option to import MetaMask from Brave even though MetaMask is not installed. This likely has to do with some similarities in terms of how Brave stores the vault file for its own wallet, but in this instance, a wallet hasn't even been created. When importing, the app throws an error (see screenshot).

### Add logs

(00:30:08) ERROR:   [Backend]:          There was an error while importing MetaMask. Error: NotFound: . Code = LEVEL_NOT_FOUND

### Steps to reproduce

.

### Expected behavior

.

### Screenshots

![Screenshot from 2023-04-19 00-31-02](https://user-images.githubusercontent.com/10467486/232968402-4f909157-c0b4-439f-8c24-53670e34063c.png)

### hyperplay Version

Latest Stable

### System Information

Linux, may affect other OSes as well

**Comment by BrettCleary** [comment]
I cannot replicate this. Where/how did you install Brave?

**Comment by awantoch** [comment]
Closing as we have since heavily modified and cleaned up the import code.
