### ISSUE TITLE
See the chain associated with a game

### ISSUE THREAD

**Issue by jacobc-eth** [HyperPlay-Gaming/hyperplay-desktop-client#270]
As a player about to launch a game, I'd like to know what chain the game uses so that I will know what chain the assets exist on and whether I'll be able to pay for gas.

**Description**

This is displaying chain information on BOTH the game's store listing page, and the games page within the launcher.

We originally discussed displaying this info on the games card itself, but have opted to hold off on that because it will make the cards too cluttered.

**AC**

* store view
* game library view
* support multiple chains in view
* show icons for popular chains
* generic EVM icon for less common chains where we don't have an icon

**Comment by pimentel08** [comment]
figma
https://www.figma.com/file/GKPELZxk551oVC3EDLgEDA/HP-Launcher?node-id=2744-19318&t=N7uKF27vEGso3jvE-4

**Comment by pimentel08** [comment]
![Screenshot 2023-05-05 at 12.18.46 PM.png](https://images.zenhubusercontent.com/63641b290f003701b0c099dc/68238c90-9b98-46ab-b52e-6f423e15847e)

**Comment by pimentel08** [comment]
Tool tip for token types

![Screenshot 2023-05-05 at 12.19.15 PM.png](https://images.zenhubusercontent.com/63641b290f003701b0c099dc/f6546d7a-dca9-41d3-a7a7-36e8ca6a7157)

**Comment by BrettCleary** [comment]
blocked by https://github.com/valist-io/valist-js/pull/378

in progress store pr https://github.com/HyperPlay-Gaming/hyperplay-store/pull/20

in progress ui pr https://github.com/HyperPlay-Gaming/hyperplay-ui/pull/38

client integration will start after merging the above PR's

**Comment by awantoch** [comment]
valist-io/valist-js#378 should be good to go now

**Comment by awantoch** [comment]
Note: HyperPlay-Gaming/hyperplay-store#20 and valist-io/hyperplay-dev#61 should be merged at the same time, or close as possible. Ideally, valist-io/hyperplay-dev#61 goes first.

valist-io/hyperplay-dev#61 changes the dev portal inputs to go straight to new review system as well as introduces the various UI changes for configuring channels and licensing. when we merge this, the old API will go stale, but the clients will still be able to fetch from it.

If we merge HyperPlay-Gaming/hyperplay-store#20 first, there's no issue, but we will have to re-run data migrations to ensure we get all of the latest data from the old dev portal, so less ideal but definitely do-able.

**Comment by BrettCleary** [comment]
This is already working in the store and should be easy to implement on the next game page frontend update.

Closing this issue as this one is more specific https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/issues/433

this is a good issue for a first time contributor/new hire
