### ISSUE TITLE
Discover web3 games in the Epic Store

### ISSUE THREAD

**Issue by jacobc-eth** [HyperPlay-Gaming/hyperplay-desktop-client#271]
As a web3 gamer, I'd like to discover the web3 games of the Epic Store while viewing the HyperPlay store, so that the web3 compatible games won't be buried in the Epic Store.

**Description**

Many web3 games rely on Epic Store services, and are currently only available in the Epic Store. This card focuses on creating listings for these games in the HyperPlay store.

Games of this type should still have both a card and a listing in the HyperPlay Store, but instead of seeing a "Add to Library" button, they should see a "Play in the Epic Store" button so they understand that they're being forwarded to the games listing in the Epic Store.

**Comment by awantoch** [comment]
The backend functionality is ready and merged via https://github.com/valist-io/hyperplay-dev/pull/52

Next up is the launcher integration :)

**Comment by awantoch** [comment]
The field is underneath a new "Advanced" dropdown on the game settings:

![image.png](https://images.zenhubusercontent.com/63c5bc80ccda843d19411770/689ab287-5c88-4087-afca-7d76dbc67abf)
