### ISSUE TITLE
See that an NFT is required to download a game

### ISSUE THREAD

**Issue by jacobc-eth** [HyperPlay-Gaming/hyperplay-desktop-client#274]
As a player trying to play a token-gated game, I'd like to see what NFT is required for me to play this game, so that I'll be able to play successfully.

**description**

this displays on the store listing page and should display the specific NFT that is required to play the game, as well as a link to where that NFT can be purchased.

**Comment by pimentel08** [comment]
See ticket [#270](https://app.zenhub.com/workspaces/hyperplay-sprint-63066f38a63278001e5c8601/issues/gh/hyperplay-gaming/hyperplay-desktop-client/270)

**Comment by awantoch** [comment]
Closing for: https://github.com/HyperPlay-Gaming/product-management/issues/49
