### ISSUE TITLE
Update modals with the new design system

### ISSUE THREAD

**Issue by biliesilva** [HyperPlay-Gaming/hyperplay-desktop-client#279]
Update modals to the designs defined in Figma.

**Comment by biliesilva** [comment]
https://www.figma.com/file/GKPELZxk551oVC3EDLgEDA/HP-Launcher?node-id=614%3A4187&t=m6TjXO8bE1G7klkm-1

**Comment by iamdavid0091** [comment]
This is now outdated. Closing this issue.
