### ISSUE TITLE
Implement Pause Downloads Queue

### ISSUE THREAD

**Issue by flavioislima** [HyperPlay-Gaming/hyperplay-desktop-client#291]
**ac**

- support Epic
- support GoG
- support HyPy store

**Comment by jacobc-eth** [comment]
Epic and GoG completed. HyperPlay store implementation is still in progress.

**Comment by flavioislima** [comment]
Finished HP implementation for pausing and also used a more reliable and full feature library to deal with HP downloads, improving the performance and reliability of the downloads in general.
