### ISSUE TITLE
MetaMask Mobile login not working

### ISSUE THREAD

**Issue by stormcakes** [HyperPlay-Gaming/hyperplay-desktop-client#297]
When trying to log in using the MetaMask mobile integration - user can complete all steps such as scanning the QR Code and authorizing the connection but the application does not recognize it. When trying to reconnect - the metamask logo on the app instead continues to spin as there is already an active connection - it just is failing to appear on the hyperplay side. 

Platform: MacOS - M1.

**Comment by BrettCleary** [comment]
this is fixed now
