### ISSUE TITLE
JSON-RPC server not working with WalletConnect

### ISSUE THREAD

**Issue by awantoch** [HyperPlay-Gaming/hyperplay-desktop-client#305]
### Describe the bug

When calling any JSON-RPC method when connected with a mobile wallet via WalletConnect, like the following:

```json
{
   "request":{
      "method":"eth_accounts"
   },
   "chain":{
      "chainId":"1"
   }
}
```

The following error is returned:

```html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<title>Error</title>
</head>

<body>
	<pre>TypeError: provider.isConnected is not a function<br> &nbsp; &nbsp;at isProviderConnected (/Applications/HyperPlay.app/Contents/Resources/app.asar/build/electron/main.js:677:245578)<br> &nbsp; &nbsp;at /Applications/HyperPlay.app/Contents/Resources/app.asar/build/electron/main.js:677:245727<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/Applications/HyperPlay.app/Contents/Resources/app.asar/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at trim_prefix (/Applications/HyperPlay.app/Contents/Resources/app.asar/node_modules/express/lib/router/index.js:328:13)<br> &nbsp; &nbsp;at /Applications/HyperPlay.app/Contents/Resources/app.asar/node_modules/express/lib/router/index.js:286:9<br> &nbsp; &nbsp;at Function.process_params (/Applications/HyperPlay.app/Contents/Resources/app.asar/node_modules/express/lib/router/index.js:346:12)<br> &nbsp; &nbsp;at next (/Applications/HyperPlay.app/Contents/Resources/app.asar/node_modules/express/lib/router/index.js:280:10)<br> &nbsp; &nbsp;at isUserAuthenticated (/Applications/HyperPlay.app/Contents/Resources/app.asar/build/electron/main.js:677:245530)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/Applications/HyperPlay.app/Contents/Resources/app.asar/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at trim_prefix (/Applications/HyperPlay.app/Contents/Resources/app.asar/node_modules/express/lib/router/index.js:328:13)<br> &nbsp; &nbsp;at /Applications/HyperPlay.app/Contents/Resources/app.asar/node_modules/express/lib/router/index.js:286:9<br> &nbsp; &nbsp;at Function.process_params (/Applications/HyperPlay.app/Contents/Resources/app.asar/node_modules/express/lib/router/index.js:346:12)<br> &nbsp; &nbsp;at next (/Applications/HyperPlay.app/Contents/Resources/app.asar/node_modules/express/lib/router/index.js:280:10)<br> &nbsp; &nbsp;at /Applications/HyperPlay.app/Contents/Resources/app.asar/node_modules/body-parser/lib/read.js:137:5<br> &nbsp; &nbsp;at AsyncResource.runInAsyncScope (node:async_hooks:202:9)<br> &nbsp; &nbsp;at invokeCallback (/Applications/HyperPlay.app/Contents/Resources/app.asar/node_modules/raw-body/index.js:231:16)</pre>
</body>

</html>
```

### Add logs

(12:47:58) INFO:    [Legendary]:        Refreshing library...
(12:47:58) INFO:    [Backend]:          Loading MetaMask extension
(12:47:58) INFO:    [Connection]:       Connectivity: check-online
(12:47:58) INFO:    [Connection]:       Pinging external endpoints
(12:47:58) INFO:    [Backend]:          Creating abort controller for legendary-version
(12:47:58) INFO:    [Legendary]:        Running command: /Applications/HyperPlay.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary --version
(12:47:58) INFO:    [Legendary]:        Legendary location: /Applications/HyperPlay.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary
(12:47:58) INFO:    [Gog]:              GOGDL location: /Applications/HyperPlay.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl
(12:47:58) INFO:    [Gog]:              GOGDL location: /Applications/HyperPlay.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl
(12:47:58) WARNING: [Backend]:          Protocol already registered.
(12:47:58) INFO:    [Backend]:          App is starting in headless mode = undefined isCLINoGui = false startInTray = undefined
(12:47:58) INFO:    [Backend]:          MetaMask extension loaded
(12:47:58) INFO:    [Connection]:       Connectivity: online
(12:47:58) INFO:    [Backend]:          User Not Found, removing it from Store
(12:47:58) INFO:    [Backend]:          Auto Updater found version: 0.1.0 released on 2023-04-18T08:52:11.048Z with name Version 0.1.0 Alpha
(12:47:59) INFO:    [Backend]:          Loading Screen Ready
(12:47:59) INFO:    [Backend]:          Frontend Ready
(12:47:59) INFO:    [Frontend]:         Refreshing Library
(12:47:59) INFO:    [Frontend]:         No cache found, getting data from legendary...
(12:47:59) INFO:    [Legendary]:        Refreshing library...
(12:47:59) WARNING: [Backend]:          listUpdateableGames not implemented on HyperPlay Library Manager
(12:47:59) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(12:47:59) INFO:    [Gog]:              Found 0 game(s) to update
(12:48:00) INFO:    [Backend]:          Deleting abort controller for legendary-version
(12:48:00) INFO:    [Backend]:          Creating abort controller for gogdl-version
(12:48:00) INFO:    [Gog]:              Running command: /Applications/HyperPlay.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --version
(12:48:02) INFO:    [Backend]:          Deleting abort controller for gogdl-version
(12:48:03) INFO:    [Backend]:          

HyperPlay Version: 0.1.0
Legendary Version:  0.20.32 Dark Energy (hotfix #6)
GOGdl Version: 0.6
OS: macOS Ventura 13.3.1 KERNEL: 22.4.0 ARCH: arm64
CPU: Apple M1 Pro @2.4 
RAM: Total: 32 GiB Available: 22.35 GiB
GRAPHICS: GPU0: Apple M1 Pro   

(12:48:04) INFO:    [Backend]:          Starting the Download Queue

### Steps to reproduce

1. Use `localhost:9680/rpc` as RPC endpoint
2. Send any payload such as `eth_accounts`
3. See error

*Note:* This does not occur when using MetaMask as the selected wallet

### Expected behavior

1. Use `localhost:9680/rpc` as RPC endpoint
2. Send a payload such as `eth_accounts`
3. Receive a response like `["address"]`

### hyperplay Version

Latest Stable

### System Information

- OS [e. g. "Ubuntu"]: macOS 13.3.1 (22E261)
- hyperplay Version [e. g. 2.1.1]: 0.1.0

**Comment by BrettCleary** [comment]
fixed by https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/pull/312
