### ISSUE TITLE
Client asks to update immediately after install, then errors when you try to update

### ISSUE THREAD

**Issue by awantoch** [HyperPlay-Gaming/hyperplay-desktop-client#306]
### Describe the bug

On Windows, if you download the HP client, then launch it for the first time, it asks you to update:
![image](https://user-images.githubusercontent.com/2301666/236904938-898495dd-87bd-4659-8339-c1106d113186.png)

Then if you try to install the update (which doesn't exist since you're already on latest) you get the following error:
![image](https://user-images.githubusercontent.com/2301666/236905104-3a6d63a2-0c91-4b8a-986d-e556286c2307.png)

### Add logs

Don't have access to this users logs yet

### Steps to reproduce

1. Download HP from website
2. Install and launch
3. See update request
4. Try to update, get error

### Expected behavior

1. Download HP from website
2. No update needed as we're on the latest version
3. If update available, should not error

### hyperplay Version

Latest Stable

### System Information

- OS [e. g. "Ubuntu"]: Windows 10 amd64
- hyperplay Version [e. g. 2.1.1]: 0.1.0

**Comment by flavioislima** [comment]
@awantoch did you have this again on v0.2.0?
