### ISSUE TITLE
Documentation: SIWE

### ISSUE THREAD

**Issue by jacobc-eth** [HyperPlay-Gaming/hyperplay-desktop-client#311]
Many developers are asking about how to use Sign-in With Ethereum with HyperPlay. This card covers to process of creating SIWE example docs for both Unity and Unreal.

**Comment by leon-do** [comment]
content updated

**Comment by leon-do** [comment]
design updated

**Comment by leon-do** [comment]
https://medium.com/@HyperPlay/c7f83ea1b8c3

**Comment by leon-do** [comment]
@Kwilke1982 added docs to https://app.gitbook.com/o/bIgjqtsIY5GMAWM4dHyK/s/EGmsOvTzE2ysXIrJyQvC/~/changes/37/developer-docs/api/rpc-endpoint/rpc-call-examples/personal-sign/sign-in-with-ethereum

great teamwork
