### ISSUE TITLE
HyperPlay Website Refresh v3

### ISSUE THREAD

**Issue by jacobc-eth** [HyperPlay-Gaming/hyperplay-desktop-client#342]
Let's implement the latest design revisions found on Figma, especially as the previous revisions contained out of date roadmap items.

https://www.figma.com/file/729ANWXb7TtDZD5mj84qbc/HP-Website?type=design&node-id=1331-682&t=IOKlIDvt4qqowcF6-0

**Comment by BrettCleary** [comment]
content is updated. we still need to switch to the new design system and update the styles to the new design though

**Comment by flavioislima** [comment]
Lowered the priority since the old content was already replaced, only the new styles and other visual changes remain.
