### ISSUE TITLE
Merge Store Badge Pages

### ISSUE THREAD

**Issue by jacobc-eth** [HyperPlay-Gaming/hyperplay-desktop-client#351]
**AC**

* Make the badge creator 4th option the default of the creator view
* Make "Download on" more prominent on the default view

**Comment by pimentel08** [comment]
![Screenshot 2023-06-19 at 4.44.38 PM.png](https://images.zenhubusercontent.com/63641b290f003701b0c099dc/fb533d17-d0d0-403b-9c03-86d478a0e025)

**Comment by pimentel08** [comment]
https://www.figma.com/file/729ANWXb7TtDZD5mj84qbc/HP-Website?type=design&node-id=1457-1267&t=28JMw9B7R2bkd35N-4

**Comment by pimentel08** [comment]
Design Change: added toggle for button background
