### ISSUE TITLE
UI: Onboard screens for SteamDeck

### ISSUE THREAD

**Issue by biliesilva** [HyperPlay-Gaming/hyperplay-desktop-client#358]
As a player who has a SteamDeck, I would like to have a HyperPlay Game Launcher onboarding screen to be accessible and smooth as possible.

**Comment by iamdavid0091** [comment]
This is captured in this [Avion story](https://game7.avion.io/map/3zsNCKL4j7Ej9eGNY/zvcxKAoiZPLzjRn2A)
