### ISSUE TITLE
Improved error dialog when game exe does not exist

### ISSUE THREAD

**Issue by BrettCleary** [HyperPlay-Gaming/hyperplay-desktop-client#364]
### Problem description

If a game developer sets their exe incorrectly or there is an issue during download/extraction, the exe path may be for a file that does not exist. 

The user receives the following dialog (as of v0.2.3) in this case
![image](https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/assets/27568879/10dffbd3-20f5-4936-9aaa-a1d39ef97e22)

which doesn't make sense to non developers.

### Feature description

Ideally in this case the user would receive a human readable/friendly message along the lines of 

"Woops! The executable at <path> does not exist! Please report this bug at https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/issues or in the HyperPlay Discord"

**Comment by nyghtstalker** [comment]
Older version of https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/issues/511
