### ISSUE TITLE
UI: HyperPlay game page for SteamDeck

### ISSUE THREAD

**Issue by biliesilva** [HyperPlay-Gaming/hyperplay-desktop-client#365]
As a player who owns a SteamDeck, I would like to have smooth navigation on the HyperPlay game page. 

- The components need some adjustments so that the content is visible horizontally, and is navigable vertically;

**Comment by biliesilva** [comment]
Fitting the spaces, this would be the UI on SteamDeck:
![SteamDeck-HyperPlay-gameStore.png](https://images.zenhubusercontent.com/632b7ad556a6e91b33441ad9/55e892ff-4e02-4621-9b36-6c9760cce568)


(Figma Link)[https://www.figma.com/file/I1sUgTrM6MZTglgiks70oe/SteamDeck-UI?type=design&node-id=2356%3A10708&t=MqNHTQPWz3MZvbBt-1]

**Comment by iamdavid0091** [comment]
This is captured in this [Avion story](https://game7.avion.io/map/3zsNCKL4j7Ej9eGNY/zvcxKAoiZPLzjRn2A)
