### ISSUE TITLE
UI: Download screen for SteamDeck

### ISSUE THREAD

**Issue by biliesilva** [HyperPlay-Gaming/hyperplay-desktop-client#367]
As a player who owns a SteamDeck, I would like to see an adapted version of the HyperPlay download screen on my SteamDeck.

- There is a need to adjust the component cells so that the font size does not exceed it, especially when it comes to language localization.

**Comment by biliesilva** [comment]
![Settings.png](https://images.zenhubusercontent.com/632b7ad556a6e91b33441ad9/e833f54d-daa5-4b56-ad63-80fbe8574496)

![Settings 2.png](https://images.zenhubusercontent.com/632b7ad556a6e91b33441ad9/7f5b8cc6-e349-4fa7-9995-769bf30e093b)

**Comment by biliesilva** [comment]
![Download manager.png](https://images.zenhubusercontent.com/632b7ad556a6e91b33441ad9/14434b85-2f8c-42d6-b159-220ac8b767c2)

![Download manager 2.png](https://images.zenhubusercontent.com/632b7ad556a6e91b33441ad9/365d7e9b-1d8e-4dea-a2e2-b75591c3843e)

**Comment by iamdavid0091** [comment]
This is captured in this [Avion story](https://game7.avion.io/map/3zsNCKL4j7Ej9eGNY/zvcxKAoiZPLzjRn2A)
