### ISSUE TITLE
add a browser based game

### ISSUE THREAD

**Issue by jacobc-eth** [HyperPlay-Gaming/hyperplay-desktop-client#371]
As a player who wants to sideload a browser game, I'd like to find an option in the Add Game modal to add a browser game.

**Comment by pimentel08** [comment]
See [ticket #372](https://app.zenhub.com/workspaces/hyperplay-sprint-63066f38a63278001e5c8601/issues/gh/hyperplay-gaming/hyperplay-desktop-client/372)

**Comment by BrettCleary** [comment]
This was added a while back. It is an option under "Select Platform". Closing this.
