### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by BrettCleary** [HyperPlay-Gaming/hyperplay-desktop-client#389]
ty for the cdn github 

![hp_screenshot_dfk](https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/assets/27568879/602f6b89-9c43-4798-aeb6-0692e0807d4a)
![hp_screenshot_onboarding](https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/assets/27568879/00bd0934-bdbd-49e0-af42-a6e32d652ca9)
![hp_screenshot_library](https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/assets/27568879/870b2329-d01a-4e19-8a18-560f302aaa38)
![hp_screenshot_store](https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/assets/27568879/83878965-21a5-4c0a-9c59-ecde17cabce5)

**Comment by jacobc-eth** [comment]
@BrettCleary do we still need this issue?
