### ISSUE TITLE
See game store by Most Popular

### ISSUE THREAD

**Issue by jacobc-eth** [HyperPlay-Gaming/hyperplay-desktop-client#392]
See the default view of the HyperPlay Store sorting games by which game is the most popular (based on analytics report).

* Most popular defined in the preceding 7 days

**Comment by BrettCleary** [comment]
I am using the "Weekly Active Players Per Game" mixpanel insight to do the popularity store rankings, and I noticed that when games change the capitalization in their names or when someone sideloads the game with different casing, it shows as a separate entry in mixpanel. 

I'm accumulating it in my nextjs function but I thought I should note this as it did change the ranking for several of the games

we should convert the game title to lower case and accumulate in mixpanel if we want perfectly accurate data there too

**Comment by awantoch** [comment]
@BrettCleary re: name capitalization, would it be better if we used the `project_name` or `account_name/project_name` instead since that's got special chars stripped and is independent of any Display Name changes?
