### ISSUE TITLE
mac overlay isn't fullscreen 

### ISSUE THREAD

**Issue by BrettCleary** [HyperPlay-Gaming/hyperplay-desktop-client#406]
### Describe the bug

for some mac games the overlay is not full screen. the height seems to not include the toolbar

### Add logs

.

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

background blur should cover the full screen

### Screenshots

![image](https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/assets/27568879/65cb8aa2-f99e-4453-9714-8aad97ec6150)

### hyperplay Version

Latest Stable

### System Information

- OS [e. g. "Ubuntu"]: mac sonoma beta
- hyperplay Version [e. g. 2.1.1]: main

**Comment by nyghtstalker** [comment]
No longer occurring.
