### ISSUE TITLE
Test WalletConnect V2

### ISSUE THREAD

**Issue by leon-do** [HyperPlay-Gaming/hyperplay-desktop-client#414]

**Comment by leon-do** [comment]
Initial Test

Metamask ❌
Argent ✅
MEW ❌
Rainbow ❌
Trust ❌

```
{"level":50,"time":1690384623550,"pid":96034,"hostname":"Leons-MacBook-Pro-16.local","err":{"type":"Error","message":"","stack":"Error\n    at /Users/leon/Desktop/hyperplay-desktop-client/node_modules/@walletconnect/ethereum-provider/dist/index.cjs.js:1:3717\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async i (/Users/leon/Desktop/hyperplay-desktop-client/node_modules/@walletconnect/ethereum-provider/dist/index.cjs.js:1:3537)"},"msg":""}
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error
    at /Users/leon/Desktop/hyperplay-desktop-client/node_modules/@walletconnect/ethereum-provider/dist/index.cjs.js:1:3717
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async i (/Users/leon/Desktop/hyperplay-desktop-client/node_modules/@walletconnect/ethereum-provider/dist/index.cjs.js:1:3537)
```

**Comment by leon-do** [comment]
PR here

https://github.com/HyperPlay-Gaming/hyperplay-proxy-server/pull/20

**Comment by leon-do** [comment]
Created separate ticket for Metamask. Needs more debugging 

https://app.zenhub.com/workspaces/hyperplay-sprint-63066f38a63278001e5c8601/issues/gh/hyperplay-gaming/hyperplay-desktop-client/418

**Comment by leon-do** [comment]
PR

https://github.com/HyperPlay-Gaming/hyperplay-proxy-server/pull/21

**Comment by BrettCleary** [comment]
this was merged here https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/commit/ea9433d7a16c816dabb564071e6dd5dca7e5e99b

**Comment by Mash-Woo** [comment]
> works `chains: [1]`
> 
> https://github.com/HyperPlay-Gaming/hyperplay-proxy-server/blob/2d7193d907e973b465872c28854c9c3be82f9349/providers/walletConnectProvider.ts#L77
> 
> Source [MetaMask/metamask-mobile#6688](https://github.com/MetaMask/metamask-mobile/issues/6688)
> 
> Metamask ❌ Argent ✅ MEW ✅ Rainbow ✅ Trust ✅

Sorry but I can't see it
