### ISSUE TITLE
Test Walletconnect v2 for Metamask

### ISSUE THREAD

**Issue by leon-do** [HyperPlay-Gaming/hyperplay-desktop-client#418]

**Comment by leon-do** [comment]
Continuation of https://app.zenhub.com/workspaces/hyperplay-sprint-63066f38a63278001e5c8601/issues/gh/hyperplay-gaming/hyperplay-desktop-client/414

**Comment by leon-do** [comment]
Submitted an issue on WC github

https://github.com/WalletConnect/walletconnect-monorepo/issues/3302

**Comment by awantoch** [comment]
@leon-do let me reach out to a buddy at WC for viz here

**Comment by leon-do** [comment]
I appreciate it @awantoch 
Got two eyes on it

**Comment by leon-do** [comment]
metadata: {
      name: "HyperPlay",
      description: "Hyperplay",
      url: "https://hyperplay.xyz/",
      icons: [""],
    },
