### ISSUE TITLE
Install modal does not display extracting

### ISSUE THREAD

**Issue by nyghtstalker** [HyperPlay-Gaming/hyperplay-desktop-client#455]
### Describe the bug

While a game is extracting the install modal still displays downloading. This should change to extracting.

Needs to display on the game card and downloads page too.

### Add logs

N/A

### Steps to reproduce

1. Install any game
2. Observe install modal shows downloading
3. Wait for the game to extract
4. Observe install modal still shows downloading

### Expected behavior

Install modal displays extracting

### Screenshots

![image](https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/assets/82125535/899c940b-95e8-4dca-9b85-e099345dcbd9)

![image](https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/assets/82125535/8d2bbb98-a47d-4d57-91cc-cbd0bdb9d9f3)

![image](https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/assets/82125535/5a7da6ff-09ce-45fc-b984-644b547e10d1)

### hyperplay Version

Latest Stable

### System Information

- OS: all
- hyperplay Version 0.4.2

**Comment by flavioislima** [comment]
@red-game-dev maybe instead of 'extracting' we could just show 'installing' or 'verifying' like Steam does. It is more user friendly than extracting imo.

**Comment by red-game-dev** [comment]
@flavioislima, we can discuss this further with @BrettCleary. Personally either of the two are fine, as letting know the user is being extracted at the moment, but perhaps for large downloaded game usually people does not really check the screen all the time, so less statuses would be better as we already have got some complexities in middle both from BE & FE 🙌 Let me know if we should discuss all this through call 🍻
