### ISSUE TITLE
Games using Proton on Linux cannot launch external browser windows

### ISSUE THREAD

**Issue by jacobc-eth** [HyperPlay-Gaming/hyperplay-desktop-client#469]
### Describe the bug

Games like Megaweapon and My Angry Yakuza Girlfriend rely on external browser windows for authentication. Currently, when these games try to trigger the browser window so the user can authenticate, nothing happens. The player cannot progress or play these games.

### Add logs

n/a

### Steps to reproduce

1. Launch MAYG or Megaweapon
2. Attempt to authenticate with Discord on Megaweapon, or attempt to connect wallet with MAYG.

### Expected behavior

a browser window, either from our electron browser or via the default browser on the device, should be opened.

### hyperplay Version

Latest Stable

### System Information

Linux

**Comment by flavioislima** [comment]
I can confirm that the issue DOES NOT happen on HyperPlay Flatpak.
I could use Proton Experimental to open links from Megaweapon just fine.

Will check the other builds.

**Comment by flavioislima** [comment]
The issue happens on the other builds of the client, AUR/TAR.XZ.

I also added MegaWeapon to Heroic and noticed the same issue.

The problem is that Proton, to handle external links, needs to be used with the Steam Runtime enabled. 

So the fix for that will be to enable the steam runtime when using proton to play.

**Comment by flavioislima** [comment]
@jacobc-eth @nyghtstalker a fix can be tested on #525 

But basically, just make sure you have Steam Runtime installed on Steam client and enable it under the game settings on the current build. With that the game should work just fine.

If you don't have Steam or the Steam runtime installed, then there is nothing we can do on our end for the links to work.

**Comment by nyghtstalker** [comment]
> @jacobc-eth @nyghtstalker a fix can be tested on #525
> 
> But basically, just make sure you have Steam Runtime installed on Steam client and enable it under the game settings on the current build. With that the game should work just fine.
> 
> If you don't have Steam or the Steam runtime installed, then there is nothing we can do on our end for the links to work.

@flavioislima The "Play/Install" button on a store game page does not work for any games. I am able to "Add to library" from the store but in order to install it I have to go to the library. I am using Gnome Arch.

**Comment by flavioislima** [comment]
This not related to my change. It only enables the steam runtime by default
when using proton, nothing else. This issue is probably affecting main as
well. I will check it tomorrow.

A sábado, 16/09/2023, 00:29, nyghtstalker ***@***.***>
escreveu:
