### ISSUE TITLE
See an animation of how to connect my wallet with a QR code

### ISSUE THREAD

**Issue by jacobc-eth** [HyperPlay-Gaming/hyperplay-desktop-client#48]
As a MetaMask Mobile user connecting to the SDK via HyperPlay, I'd like to see an animation of how to connect my wallet with a QR code, so that I will know that I need to scan the QR code from within the MM Mobile app.

**description**

Currently, MetaMask Mobile's SDK isn't working if the user scans the QR code from the default android camera app. This story is meant to make sure users don't make this mistake before the MetaMask team resolves the issue.

**Comment by iamdavid0091** [comment]
@jacobc-eth I believe this issue was resolved from MetaMask's end. Can you confirm?

**Comment by jacobc-eth** [comment]
Yeah this is no longer needed since the camera app works
