### ISSUE TITLE
See that HyperPlay is loading

### ISSUE THREAD

**Issue by jacobc-eth** [HyperPlay-Gaming/hyperplay-desktop-client#494]
One of the most common UX problems users are experiencing is that when clicking a game, the store takes a few seconds to load. Currently, no validation is shown when the user clicks on a game card, so it is unclear that the application is actually successfully loading, causing the user to click multiple times and to think that HyperPlay is broken.

**Comment by pimentel08** [comment]
[Figma page link](https://www.figma.com/file/GKPELZxk551oVC3EDLgEDA/HP-Launcher?type=design&node-id=5007-5056&mode=design&t=WVEYXYyzLwo41XwE-4)

![Image](https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/assets/93540327/ae15a149-40c0-4ecb-bf99-b7d5a94494e8)

**Comment by BrettCleary** [comment]
can we move this issue to the store repo :) 

There is a in review/testing PR in the store that needed to come before this

**Comment by BrettCleary** [comment]
Can we reverify that this is an issue? We now have prefetching enabled for this route

**Comment by nyghtstalker** [comment]
When clicking a store game card the user is taken straight to the store game page and all the content is immediately loaded. The YouTube video may take a second or two to fully load but all other info is displayed immediately. I can't find any delay or unrendered content when going to a store game page.
