### ISSUE TITLE
HyperPlay website preview image is not web optimized

### ISSUE THREAD

**Issue by jacobc-eth** [HyperPlay-Gaming/hyperplay-desktop-client#507]
Currently, when sharing link to the HyperPLay website, the preview image is currently over 3MB, causing the image to not even render in many instances. This image should be optimized to below 250kb.

https://hyperplay.xyz/HyperPlayOpenGraphCard.png 

![image](https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/assets/82125535/47cf6164-ef96-4acb-8954-21eb0522cbb7)

**Comment by jacobc-eth** [comment]
Pinging @pimentel08 and @biliesilva since I just noticed this image is also showing the old product UI.

**Comment by pimentel08** [comment]
Addressed in new ticket [#43](https://github.com/orgs/HyperPlay-Gaming/projects/1/views/1?pane=issue&itemId=46246638)
