### ISSUE TITLE
Improve CI workflows with Caching

### ISSUE THREAD

**Issue by flavioislima** [HyperPlay-Gaming/hyperplay-desktop-client#509]
- Implement Caching on build and release workflows for artifacts
- Implement Caching on all workflows for Dependencies.

**Comment by BrettCleary** [comment]
Here's some example code when I was exploring this on the website @flavioislima . https://github.com/HyperPlay-Gaming/hyperplay-website/commit/3f25030630f89c3d58198d56e41e0289032f4546
