### ISSUE TITLE
Overlay launches when game hasn't launched

### ISSUE THREAD

**Issue by jacobc-eth** [HyperPlay-Gaming/hyperplay-desktop-client#547]
Multiple issues are reporting an issue that seems to have begun with 0.6.0 where the overlay fires for non-game related launches. For example, if the user launches a game that installs third-party libraries, the overlay fires during the install of those libraries (see screenshot).

![Image](https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/assets/10467486/10534cc2-07e9-4ed5-840c-c6ba0012b44c)

**Comment by awantoch** [comment]
Duplicate of #537 -- see explanation here: https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/issues/537#issuecomment-1726674953

**Comment by awantoch** [comment]
Closing this for #537
