### ISSUE TITLE
Fix and Improve Linux SNAP package

### ISSUE THREAD

**Issue by flavioislima** [HyperPlay-Gaming/hyperplay-desktop-client#548]
Epic games that rely on compatibility layer do not work via SNAP package. A support ticket has been created in the Snap forums and we're getting more info.

**Comment by awantoch** [comment]
Heroic changes first will inform/make this easier for HP's changes

**Comment by flavioislima** [comment]
Closing this one since we won't support Linux Snap anymore.
Pr for removing it from the website: https://github.com/HyperPlay-Gaming/website/pull/62
