### ISSUE TITLE
Mouseover on the Store Page library menu item does not change the font and curser

### ISSUE THREAD

**Issue by nyghtstalker** [HyperPlay-Gaming/hyperplay-desktop-client#550]
### Describe the bug

When a user mouses over the Store Page item in the Library menu the font color and curser does not change like it does with the rest of the items in the menu list.

### Add logs

N/A

### Steps to reproduce

1. Go to any game in the library
2. Open menu
3. Mouse over "Store Page"
4. Observe not change on mouseover

### Expected behavior

Store Page should have the same mouseover result as all other items in the list

### Screenshots

![image](https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/assets/82125535/9c72e9f3-19e8-40ce-8d8e-7a01dc34c2ee)

![image](https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/assets/82125535/49db568a-9038-4426-99c9-aee23f00e3ba)

### hyperplay Version

Latest Stable

### System Information

- Windows 10
- hyperplay Version 0.6.0

**Comment by iamdavid0091** [comment]
This has been resolved
