### ISSUE TITLE
[UI Bug] Installing wine changes table width dynamically

### ISSUE THREAD

**Issue by BrettCleary** [HyperPlay-Gaming/hyperplay-desktop-client#556]
When installing wine, the table width changes rapidly as the % completion text is updated.

The "Compatibility Layer" text shouldn't be there either

before
![image](https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/assets/27568879/dbbf301f-df43-41a0-a64e-b6125b49edb3)

during installation
![image](https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/assets/27568879/a3124c80-7f29-4d43-822d-635578f8e030)

**Comment by nyghtstalker** [comment]
This looks to be fixed.



![Image](https://github.com/user-attachments/assets/df29b0df-2ea2-4466-b77d-9d7485d98cba)
