### ISSUE TITLE
Connect multiple wallet methods to HyperPlay

### ISSUE THREAD

**Issue by jacobc-eth** [HyperPlay-Gaming/hyperplay-desktop-client#58]
As a HyperPlay user with multiple wallet connections (ie. extension and mobile), I'd like to select which method to use when launching a game, so that I'll be using the wallet I prefer and any platform specific features will be available.

**Description**
Users may have multiple wallets connections (i.e. extension and mobile) and may want to use a specific wallet for specific games for various reasons like separating reputation / assets by wallet. Users should be able to select their preferred, connected wallet for any game they launch as part of launching that game. 

**AC**
* Pop up before launching game with: 
    - current wallet address 
    - ability to click on current wallet address and choose an alternative connected wallet from a drop down list of connected wallets 
     - confirm button that then proceeds to launch the game with the selected wallet address connected

**Comment by pimentel08** [comment]
Will we be able to pull in avatars from non-MetaMask wallets or continue to use jazzicons? 

If a user connects their wallet (account 1) through MM browser extension, will they be able to connect their (account 2) via MM mobile and have those two wallet connections persist? 

Will we be able to detect which account within each wallet the player connected or just the method i.e. browser, mobile, wallet name (Rainbow)?

**Comment by pimentel08** [comment]
Feedback/Open questions:

- We cannot show which wallet account (ie. MM wallet account 2), we can only show connection type (mobile, extension, etc)
- Wallet avatar is generated based on the wallet address not on the wallet company (MM vs Rainbow etc)
- What happens if a user loses wallet connection? 
- How will this work with SIWE?

**Comment by jacobc-eth** [comment]
Looks like this card went stale since it was in engineering ready, but it should actually be in design ready.

"Will we be able to pull in avatars from non-MetaMask wallets or continue to use jazzicons? Can we pull in Rainbow avatar or CoinbaseWallet avatar etc?"

I think keeping the blockies logos work.

"If a user connects their wallet (account 1) through MM browser extension, will they be able to connect their (account 2) via MM mobile and have those two wallet connections persist? Currently, if we connect one account and try to connect a second account, the first account is disconnected."

Yes, the goal would be to allow the user multiple wallet connections, and then to select which wallet have an active connection.

"Will we be able to detect which account within each wallet the player connected or just the method i.e. browser, mobile, wallet name (Rainbow)? What additional information can we give the user, so that they have more context about each wallet that they have connected?"

We should be able to detect which account within the wallet is active.
