### ISSUE TITLE
[CI/CD] Update Windows Release

### ISSUE THREAD

**Issue by BrettCleary** [HyperPlay-Gaming/hyperplay-desktop-client#590]
A couple small fixes are needed here to completely automate the windows release

1. The draft release name needs to be changed on the windows release workflow to `0.7.0` to match the rest of the artifacts. Right now it is `Release 0.7.0` and then we have to copy the artifacts over
2. The windows release is named `HyperPlay-Setup.exe` instead of `HyperPlay-0.8.0-Setup-x64.exe`
3. The latest.yml needs the release name updated also to `HyperPlay-0.8.0-Setup-x64.exe`
4. The latest.yml needs the sha512 hash to be all lower case. It is currently all upper case which would break auto update on windows

**Comment by flavioislima** [comment]
1. Now sure how to do that, using the powershell extension from Signpath it could not recognize something like `HyperPlay*.exe` like before when uploading the artifact.
4. SHASUM is not case sensitive, if auto-update on windows is not working then its another reason. But I tried on win11 and worked fine.
