### ISSUE TITLE
[CI/CD] Update Snap Release

### ISSUE THREAD

**Issue by BrettCleary** [HyperPlay-Gaming/hyperplay-desktop-client#593]
When releases are still in draft, they are released to the snap store. This can cause inconsistencies in our deployed versions as tags are often deleted and re-pushed for last minute fixes

we should use the following workflow trigger for snapcraft upload like we do for `release_flathub.yml`
```
on:
  release:
    types: [published]
```

<img width="1147" alt="image" src="https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/assets/27568879/148c5133-9721-4a42-af19-cc1579c15fb3">
<img width="971" alt="image" src="https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/assets/27568879/1526968e-53bb-4e15-be97-b8e56d09bf9f">

**Comment by flavioislima** [comment]
Fixed by #595
