### ISSUE TITLE
Add more in-depth events

### ISSUE THREAD

**Issue by awantoch** [HyperPlay-Gaming/hyperplay-desktop-client#597]
We need to add the following events in the download manager:

- Install Paused
- Install Resumed
- Install Canceled

We also need to tweak the Install Failure event to not include pausing and canceling, as it conflates those currently.

The Game Launched event is also intermittently being emitted.

**Comment by flavioislima** [comment]
The events can be seems on the screenshot from Rudderstack.
Also, as we can see on it, canceling the downloads sends a fail event as well. So maybe that is why we have so many fail events.


![Image](https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/assets/26871415/35d0dee3-36bd-4f6f-b78a-482467e65a1e)
