### ISSUE TITLE
Update on game card do not work

### ISSUE THREAD

**Issue by nyghtstalker** [HyperPlay-Gaming/hyperplay-desktop-client#635]
### Describe the bug

When a user attempts to update a game via the Update menu option or update icon on the library game card it will have no effect.

### Add logs

N/A

### Steps to reproduce

1. Go to the library
2. Find any game that needs an update
- You can change the version in the json and then refresh the library
3. Click the Update menu option or the Update icon
4. Observe nothing happens

### Expected behavior

Update is triggered

### Screenshots

![image](https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/assets/82125535/60ea2c45-09ea-4e26-89dc-5b11e8244915)

### hyperplay Version

Latest Stable

### System Information

- Windows 10
- hyperplay Version 0.8.1

**Comment by flavioislima** [comment]
Fixed by #622
