### ISSUE TITLE
[UI] Black background behind refresh icon

### ISSUE THREAD

**Issue by BrettCleary** [HyperPlay-Gaming/hyperplay-desktop-client#677]
We should refactor to use the HyperPlay UI Loading component instead of the Loading Icon with black background component in the client

![image](https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/assets/27568879/7b66835e-3693-4604-887f-ce88cc1a16a4)

**Comment by BrettCleary** [comment]
This is also the case on the docs page when loading

**Comment by nyghtstalker** [comment]
No longer occurs.
