### ISSUE TITLE
[Bug] Installing to a restricted folder on Windows

### ISSUE THREAD

**Issue by BrettCleary** [HyperPlay-Gaming/hyperplay-desktop-client#678]
# Steps
1. Add a game
2. Click Install
3. Create a folder in `C:\Program Files\HyperPlay Games`
4. Click Install
5. Observe the following error message

```
Error while downloading and extracting game: Error: EPERM: operation not permitted, mkdir 'C:\Program Files\HyperPlay Games\...'
```

**Comment by flavioislima** [comment]
It seems that `fs.access` has a but on Windows when checking for write permissions, so it was not working there.
I found a workaround now by trying to write a file on the folder and if it fails HP shows the warning:

![image](https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/assets/26871415/c065f0d1-5368-4325-b4f0-c1475898d007)

![image](https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/assets/26871415/a99ab330-56ff-4595-a594-08a5b1990454)
