### ISSUE TITLE
Design System

### ISSUE THREAD

**Issue by pimentel08** [HyperPlay-Gaming/hyperplay-desktop-client#68]
Create a design library that contains all necessary components:

- Fonts (size, weight, height, tracking)
- Color palette 
- Elements
- Components

[Figma file](https://www.figma.com/file/dTcFXy2c3vPpBnlGh4TZPY/Unreal-Library?node-id=1%3A10&t=rCo8rFiRnDKiruwI-1)

**Comment by jacobc-eth** [comment]
Close, as this card has been decomposed.
