### ISSUE TITLE
[Bug] Setting Experimental Features

### ISSUE THREAD

**Issue by BrettCleary** [HyperPlay-Gaming/hyperplay-desktop-client#681]
Experimental features handler is calling setState inside a useEffect for infinite recursion

error msg: 
```
Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.
``` 

![image](https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/assets/27568879/cbce3248-2e3f-44e5-b0de-84b56f76ae7a)

**Comment by nyghtstalker** [comment]
No longer occurring.
