### ISSUE TITLE
[Tech] Build ESM instead of commonjs

### ISSUE THREAD

**Issue by BrettCleary** [HyperPlay-Gaming/hyperplay-desktop-client#682]
Electron now supports ESM and top level await https://www.electronjs.org/blog/electron-28-0#new-features

We will have to update import logic to accommodate 

More info: https://www.electronjs.org/docs/latest/tutorial/esm

**Comment by nyghtstalker** [comment]
This is an idea that we might implement down the road. Can reopen in the future if needed.
