### ISSUE TITLE
Unable to clone sub modules

### ISSUE THREAD

**Issue by ChainCombat** [HyperPlay-Gaming/hyperplay-desktop-client#725]
![Screenshot (10)](https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/assets/158816011/ca4aa578-1d7f-4ce3-b981-45acfa8d3b6c)
after cloning, if i use the git submodule update --init --recursive flag, it opens up the github credential manager. after signing in, it still reopens the github credential manager. something like a loop. ive tried installing submodules whilst cloning too, same story.

**Comment by BrettCleary** [comment]
Hello. Thank you taking the time to explore contributing to HyperPlay 🙏 We recently removed the submodules. Could you try to clone again?

Feel free to create a new issue if you have another problem 👍
