### ISSUE TITLE
Prereq install popup after game extraction does not popup on screen

### ISSUE THREAD

**Issue by nyghtstalker** [HyperPlay-Gaming/hyperplay-desktop-client#727]
### Describe the bug

The prereq install that comes at the end of extraction does NOT pop up on the screen once it is ready. It can easily be missed and if it is missed the extraction "seems to be stuck" and doesn't finish.

### Add logs

N/A

### Steps to reproduce

1. Install the Unfettered
2. Wait for the extraction to complete
3. Observe the pop up does not appear on the screen

### Expected behavior

Popup should appear on screen and now wait for the user to select it

### Screenshots

![image](https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/assets/82125535/1bb41bfb-1804-405e-bbc8-4bff3ea051a5)

### hyperplay Version

Latest Stable

### System Information

- Windows 10
- hyperplay Version 0.11

**Comment by iamdavid0091** [comment]
Needs some investigation to see if this is even feasible.

**Comment by flavioislima** [comment]
> Needs some investigation to see if this is even feasible.

Putting the setup of pre-requesites like this on the screenshot I am not sure its doable.
In case it is not we should at least change the 'Extracting' to 'Install Pre-requisites'.
