### ISSUE TITLE
[macOS] After the app is updated, the installed version is always Intel

### ISSUE THREAD

**Issue by eliobricenov** [HyperPlay-Gaming/hyperplay-desktop-client#732]
Users that have ARM versions of the app get installed the Intel version after updating from the app.

**Comment by eliobricenov** [comment]
Solved by @flavioislima:

>Found the issue with the ARM macOS upgrading to Intel. The issue is that we have two github actions, one for every version so the latest one was overwriting the file latest-mac.yml that contains the information about the update.
the solution is simple but we will need to comunicate to all macOS users on M1+ to download HyperPlay again from the website. 
No need to uninstall, just replace the current App. No data loss or anything will happen.

**Comment by eliobricenov** [comment]
It looks like it is not solved.

**Comment by flavioislima** [comment]
> It looks like it is not solved. 

It should be solved but we need to test the artifact.
Keep it open until we merge it.

**Comment by flavioislima** [comment]
Should be solved now by #755
