### ISSUE TITLE
Show old avatar if the auth flow flag is disabled

### ISSUE THREAD

**Issue by eliobricenov** [HyperPlay-Gaming/hyperplay-desktop-client#733]
Right now we're displaying if they haven't logged in. When the auth flag is disabled they can never log in, we should show the old one instead.

current:
![Image](https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/assets/38574891/99d07cf4-3a9a-4544-a77e-c2fc395c2b00)

old:
![Image](https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/assets/38574891/9415955b-f98b-41e4-9aef-95dd75c3d9ef)

**Comment by nyghtstalker** [comment]
This is no longer occurring.
