### ISSUE TITLE
Client downloads to C: even when default install path is a different drive

### ISSUE THREAD

**Issue by awantoch** [HyperPlay-Gaming/hyperplay-desktop-client#737]
It appears that when the default install path is changed, the game is still initially being downloaded to the C: drive

This is likely due to using a tmp folder to download the ZIP.

We need to tweak the logic to use the configured drive for the initial download.

![Image](https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/assets/2301666/15a50bb1-47c9-4d4a-b15b-d38508e5b3ad)

![Image](https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/assets/2301666/2670bf56-2a66-47d3-971b-0d807c4e48a6)

**Comment by flavioislima** [comment]
I think we have discussed this in the past.
Both approaches has good and bads.
If we put the temp file on the destination drive, this also means the user will need double the space to install it so it will still breaks if it doesn't.

I'm fine with any approach but that does not solve the root problem.

For this we would need a way to download the game assets in chunks and extract and delete them in real time, so we would need maybe only 1/5 of the game space and would cause less issues.


Maybe something we could try once we have the patch service.

**Comment by awantoch** [comment]
@flavioislima I def agree that it won't fix the root cause of having to download the zip in full before extraction.

However, the current implementation causes a good bit of confusion. Right now the following flow is causing some issues:

1. Change install path to another drive, say, D:
2. Click install
3. Space left is checked on D:
4. ZIP is downloaded to C:, but the space was not checked on that drive, so the download can fail mid-way when C: is filled

Whereas, if the temp folder was on the same drive as the config'd install path, the player would at least know up-front a bit better, ofc not perfect since we don't know the full extraction size, but it would eliminate a majority of the cases that people are running into.

**Comment by awantoch** [comment]
Looks like this one arises from: https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/blob/7053effb5f685d32cec3ce8b5cdbaadb4809486b/src/backend/storeManagers/hyperplay/games.ts#L562

Here, we'll need to pull the temp folder from the settings instead of using appData always

**Comment by awantoch** [comment]
PR: https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/pull/742/files

**Comment by awantoch** [comment]
New PR instead: https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/pull/744
