### ISSUE TITLE
Ask player to configure default install path during setup on Windows

### ISSUE THREAD

**Issue by awantoch** [HyperPlay-Gaming/hyperplay-desktop-client#740]
Tangentially related to https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/issues/737

Currently, the default install path is only in the Settings.

However, since Windows users often have multiple drives, and change their install paths, the installer/setup process should also ask the player up front where to install games.

Since other OS' don't have this need as frequently (i.e., macOS users rarely have different drives/partitions), this is only needed for the Windows installer.

**Comment by nyghtstalker** [comment]
This is no longer occurring.
