### ISSUE TITLE
Ledger blind signing always requested regardless of setting

### ISSUE THREAD

**Issue by awantoch** [HyperPlay-Gaming/hyperplay-desktop-client#750]
Some users are reporting that when going to sign to claim the [Linea Park Unfettered NFT](https://layer3.xyz/quests/the-unfettered-quest), they see an error message requesting them to enable Blind Signing in their Ledger, even when they have it enabled. 

This prevents them from minting the NFT after the gameplay.

![Image](https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/assets/2301666/8fccf091-c890-46d9-8d4b-c6f16542d285)

**Comment by BrettCleary** [comment]
This is user error. I was able to replicate with my Ledger

Here is my support message template

Here are the steps to get transaction requests working with your Ledger

1. Make sure your Ledger is on the latest firmware
2. Unlock and open the Ethereum app on your Ledger
3. Click the right button until you reach settings
4. In settings, enable blind signing
5. Connect your Ledger with MetaMask and switch to this account
6. You should see a request like shown in the attached image. Click "Go to the full screen to connect your Ledger"


![Image](https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/assets/27568879/734b4dc8-6939-4a3c-80e3-98b8225abe42)


7. You will be redirected to the MetaMask home page. Click "Click here to connect you Ledger via WebHID"


![Image](https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/assets/27568879/051a1fb6-4087-45e1-bb96-66ca401a5648)


8. The confirm button should be clickable now
9. After clicking confirm, the transaction should show up on your Ledger

Please let me know if this works for you

**Comment by awantoch** [comment]
Fixed via ^^
