### ISSUE TITLE
[CI] store client artifacts metadata

### ISSUE THREAD

**Issue by eliobricenov** [HyperPlay-Gaming/hyperplay-desktop-client#754]
We recently experienced an issue where were intermittently getting an error when we tried to get the latests releases artifacts via Github API: https://api.github.com/repos/HyperPlay-Gaming/hyperplay-desktop-client/releases/latest in the download page.

We could store the metadata of the releases in a different place that we can use as fallback source in case the Github API requests fails.

**Comment by eliobricenov** [comment]
We can use a Github actions triggered by a release published event:
```yml
on:
  release:
    types: [published]
```

The caveat of doing this is that we'd need to refactor our release workflows and use a single `relase.yml` file to make sure that the step that pushes the metadata to the storage is always the last.

**Comment by eliobricenov** [comment]
We could store the metadata as a json file using Supabase storage. We can retrieve it later via the API.

**Comment by nyghtstalker** [comment]
No longer occurring.
