### ISSUE TITLE
MM extension is not connecting to Web3Modal

### ISSUE THREAD

**Issue by nyghtstalker** [HyperPlay-Gaming/hyperplay-desktop-client#756]
### Describe the bug

When playing Looperland through HP and with the wallet connected they are unable to connect the MM extension in-game.

### Add logs

N/A

### Steps to reproduce

1. Install Looperlands (browser game)
2. Launch game
3. Click "Connect wallet" in the top-right corner
4. Click "Metamask"
5. Click "Browser"

### Expected behavior

MM extension should connect

### Screenshots

![image](https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/assets/82125535/77790558-2883-4d6e-8dae-b30721845126)

![image](https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/assets/82125535/7f895e78-e36b-40a9-9b18-f428bb7e68fe)

![image](https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/assets/82125535/296e07d4-1101-4adb-af88-f1aaa31e42ca)

### hyperplay Version

Latest Stable

### System Information

- Windows 10
- hyperplay Version 0.11.2

**Comment by BrettCleary** [comment]
this was solved on https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/pull/918
