### ISSUE TITLE
UI: <add game> pop-up(s)

### ISSUE THREAD

**Issue by pimentel08** [HyperPlay-Gaming/hyperplay-desktop-client#80]
As a gamer with a Web3 game already installed on my machine, I want an easy form where I can add my game to my HyperPlay Library, so that Web3 gamers can find and launch my game there. 

**AC**
MVP Input Fields:

- Game hero image
- Game title
- Platform(s)
- Select executable
- Web3 checkbox
- CTA / Submit Button

States:
- Default
- Error message
- Filled

[Figma Link](https://www.figma.com/file/GKPELZxk551oVC3EDLgEDA/Game-Launcher?node-id=1395%3A13522&t=ALoigxEcCpDzVoup-4)

**Comment by jacobc-eth** [comment]
closing this since thisi s a very old card and we already have this functionality.
